INSERT INTO TASK (ID, CREATED_DATE, MODIFIED_DATE, TODO) VALUES(1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '집안일')
INSERT INTO TASK (ID, CREATED_DATE, MODIFIED_DATE, TODO) VALUES(2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '빨래')
INSERT INTO TASK (ID, CREATED_DATE, MODIFIED_DATE, TODO) VALUES(3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '청소')
INSERT INTO TASK (ID, CREATED_DATE, MODIFIED_DATE, TODO) VALUES(4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '방청소')

INSERT INTO RELATION (ID, MASTER_ID, SUB_ID) VALUES (1, 1, 2);
INSERT INTO RELATION (ID, MASTER_ID, SUB_ID) VALUES (2, 1, 3);
INSERT INTO RELATION (ID, MASTER_ID, SUB_ID) VALUES (3, 1, 4);
INSERT INTO RELATION (ID, MASTER_ID, SUB_ID) VALUES (4, 3, 4);